name: "Unit Tests"

on:
  push:
    branches:
      - '**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Running unit tests"
    runs-on: ubuntu-latest
    environment: "testing"

    steps:
    - uses: awalsh128/cache-apt-pkgs-action@latest
      name: Install required packages
      with:
        packages: flex bison ninja-build cmake clang libsdl2-dev libopenal-dev
        version: "${{ runner.os }}-${{ runner.arch }}-unittest-v1"

    - uses: actions/checkout@v4
      with:
        path: 'source'

    - name: Settings
      working-directory: ${{github.workspace}}
      run: |
        echo "CMAKE_GENERATOR=Ninja Multi-Config" >> $GITHUB_ENV
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
        echo "CMAKE_PARAM=--log-level=VERBOSE \
        -DCMAKE_INSTALL_PREFIX='${{github.workspace}}/install'" \
        -DUSE_RENDERER_DLOPEN=OFF \
        -DBUILD_RENDERER_GL2=OFF >> $GITHUB_ENV

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: |
        cmake -B ./build ${{ env.CMAKE_PARAM }} ./source

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        cmake --build ${{github.workspace}}/build --config Debug --parallel

    - name: Test
      working-directory: ${{github.workspace}}
      run: |
        cd "${{github.workspace}}/build"
        ctest -C Debug --output-on-failure
